// an example to create a new mapping `ctrl-y`
/*mapkey('<Ctrl-y>', 'Show me the money', function() {
    Front.showPopup('a well-known phrase uttered by characters in the 1996 film Jerry Maguire (Escape to close).');
});*/

// an example to replace `T` with `gt`, click `Default mappings` to see how `T` works.
//map('gt', 'T');

//mapkey('J', '<PageDown>');
//mapkey('J', '<Ctrl-d>');
//mapkey('K', '<PageUp>');
//mapkey('K', '<Ctrl-u>');
//map('J', '10j'); // prefixes not yet supported in keybindings
//map('K', '10k'); // prefixes not yet supported in keybindings
//map('D', '99>>'); // prefixes not yet supported in keybindings
//map('U', '99<<'); // prefixes not yet supported in keybindings
//map('gh', 'g#');
//map(':D', 'ab');
map('fd', '<Esc>');
imap('fd', '<Esc>');
vmap('fd', '<Esc>');
cmap('fd', '<Esc>');
mapkey('<Ctrl-m>', '<Esc>');
cmap('<Ctrl-j>', '<Tab>');
cmap('<Ctrl-k>', '<Shift-Tab>');
map('H', 'S');
map('L', 'D');
map('J', '10j');
map('K', '10k');
map(';', '<Ctrl-6>');
map('T', 't');
map('ma', 'm');
map('ql', 'gx$');
map('qh', 'gx0');
map('qL', 'gxT');
map('qH', 'gxt');
map('ga', 'gT');
map('gl', 'gt');
map('gj', 'gd');
mapkey('gE', '#12Open Chrome Settings', function() {
    tabOpenLink("chrome://extensions/shortcuts");
});
mapkey('gS', '#12Open Chrome Settings', function() {
    tabOpenLink("chrome://settings");
});
map('fa', 'af');
map('fi', 'gf');
map('!', 'F');
map('F', 'cf');
map('P', 'yg');
//map('<', '<<');
//map('>', '>>');
map('u', '<<');
map('d', '>>');
aceVimMap('fd', '<Esc>', 'insert');
aceVimMap('gl', '$', 'normal');
aceVimMap('gh', '^', 'normal');
aceVimMap('a', '^', 'normal');
aceVimMap('ga', '0', 'normal');
aceVimMap('e', 'E', 'normal');
aceVimMap('b', 'B', 'normal');

settings.scrollStepSize = 210;

// set theme
settings.theme = `
.sk_theme {
    font-family: Input Sans Condensed, Charcoal, sans-serif;
    font-size: 10pt;
    background: #24272e;
    color: #abb2bf;
}
.sk_theme tbody {
    color: #fff;
}
.sk_theme input {
    color: #d0d0d0;
}
.sk_theme .url {
    color: #61afef;
}
.sk_theme .annotation {
    color: #56b6c2;
}
.sk_theme .omnibar_highlight {
    color: #528bff;
}
.sk_theme .omnibar_timestamp {
    color: #e5c07b;
}
.sk_theme .omnibar_visitcount {
    color: #98c379;
}
.sk_theme #sk_omnibarSearchResult ul li:nth-child(odd) {
    background: #303030;
}
.sk_theme #sk_omnibarSearchResult ul li.focused {
    background: #3e4452;
}
#sk_status, #sk_find {
    font-size: 20pt;
}`;

// an example to remove mapkey `Ctrl-i`
//unmap('<Ctrl-i>');

unmap('cc');
unmap('p');
unmap('w');
unmap('t');
unmap('R');
unmap('D');
unmap('h');
unmap('l');
unmap(';');
unmap(',');
unmap('.');

//unmapAllExcept(['f', '/', '?']);
//unmapAllExcept(['<Esc>', '<Ctrl-i>', 'i', 'yg', 'ZZ', 'ZR', 'ZQ', 'ab', '<<', '>>']);


// click `Save` button to make above settings to take effect.