;; -*- coding: utf-8; lexical-binding: t; -*-

(clear-abbrev-table global-abbrev-table)

(define-abbrev-table 'global-abbrev-table
  '(

    ;; internet abbrev
    ("cam" "Cameron" )
    ("cac" "Cameron Chandoke" )
    ("afaik" "as far as i know" )
    ("atm" "at the moment" )
    ("dfb" "difference between" )
    ("ty" "thank you" )
    ("ui" "user interface" )
    ("uns" "understand" )
    ("ur" "you are" )
    ("btw" "by the way" )
    ("ie" "i.e.," )
    ("eg" "e.g.," )

    ("cant" "can't" )
    ("didnt" "didn't" )
    ("dont" "don't" )

    ;; english word abbrev
    ("ann" "announcement" )
    ("arg" "argument" )
    ("autom" "automatic" )
    ("bc" "because" )
    ("bg" "background" )
    ("bt" "between" )
    ("math" "mathematics" )

    ;; computing
    ("ahk" "AutoHotkey" )
    ("cfg" "context-free grammar" )
    ("cj" "Clojure" )
    ("csi" "computer science" )

    ;; tech company
    ("gc" "Google Chrome" )
    ("gm" "Google Map" )
    ("macos" "Mac OS" )
    ("msw" "Microsoft Windows" )

    ;; programing
    ("ev" "environment variable" )
    ("ipa" "IP address" )
    ("jvm" "Java Virtual Machine" )
    ("rsi" "repetitive-strain injury" )
    ("subdir" "sub-directory" )
    ("subf" "sub-folder" )
    ("wd" "web development" )

    ("db" "database" )
    ("guif" "graphical user interface" )
    ("gui" "GUI" )
    ("oopf" "object oriented programing" )
    ("oop" "OOP" )

    ("osf" "operating system" )
    ("os" "OS" )

    ;; programing
    ("eqe" "==" )
    ("ret" "return" )
    ("utf8" "-*- coding: utf-8 -*-" )

    ;; regex
    ("xaz" "\\([A-Za-z0-9]+\\)" )
		;; TODO: add more regular expressions here!!!

    ;; unicode
    ("mda" "—" )
    ("nda" "–" )
    ("dlim" "-----------------------------------------------------------------------------------" )
    ("bul" "•" )
    ("aub" "↥" )
    ("arb" "↦" )
    ("alb" "↤" )
    ("adb" "↧" )


    ;; Mathematics
    ("I" "∩" )
    ("U" "∪" )
    ("C" "⊂" )
    ("Cb" "⊆" )
    ("Cl" "⊃" )
    ("Cbl" "⊇" )
    ;; ("all" "∀" )  ; commented-out so I don't accidentally use it for my Racket "all" function, which is prettified as '∀'
    ("exi" "∃" )
    ("any" "∃" )
    ("some" "∃" )
    ("nex" "∄" )
    ("none" "∄" )
    ("in" "∈" )
    ("nin" "∉" )
    ("cont" "∋" )
    ("ncon" "∌" )
    ("o" "∘" )
    ("and" "∧" )
    ("or" "∨" )
    ("nor" "⊽" )
    ("nand" "⊼" )
    ("xor" "⊻" )
    ("thr" "∴" )
    ("ther" "∴" )
    ("bec" "∵" )
    ("em" "∅" )
    ("cro" "⨯" )
    ("grs" "⩾" )
    ("les" "⩽" )
    ("ge" "≥" )
    ("le" "≤" )
    ("not" "¬" )
    ("nega" "⌙" )
    ("abs" "∣" )
    ("neq" "≠" )
    ("E" "∑" )
    ("P" "∏" )
    ("cop" "∐" )
    ("cop'" "⨿" )
    ("G" "𝚪" )
    ("l" "λ" )
    ("pi" "𝛑" )
    ("eu" "ℯ" )
    ("g" "𝛄" )
    ;; ("est" "℮" )
    ("cirp" "⊕" )
    ("cirx" "⊗" )
    ("map" "↦" )
    ("_1" "₁" )
    ("_2" "₂" )
    ("_3" "₃" )
    ("_4" "₄" )
    ("_5" "₅" )
    ("_6" "₆" )
    ("_7" "₇" )
    ("_8" "₈" )
    ("_9" "₉" )
    ("_m" "₋" )
    ("_p" "₊" )
    ("_(" "₍" )
    ("_)" "₎" )
    ("^1" "¹" )
    ("^2" "²" )
    ("^3" "³" )
    ("^4" "⁴" )
    ("^5" "⁵" )
    ("^6" "⁶" )
    ("^7" "⁷" )
    ("^8" "⁸" )
    ("^9" "⁹" )
    ("^m" "⁻" )
    ("^p" "⁺" )
    ("^(" "⁽" )
    ("^)" "⁾" )
    ("^i" "ⁱ" )
    ("^n" "ⁿ" )
    ;; ("inte" "∫" )
    ;; ("ii" "∬" )
    ;; ("iii" "∭" )
    ;; ("iiii" "⨌" )
    ;; ("io" "∮" )
    ;; ("iio" "∯" )
    ;; ("iiio" "∰" )
    ;; ("icl" "∱" )
    ;; ("iacl" "⨑" )
    ;; ("iocl" "∲" )
    ;; ("ioacl" "∳" )
    ;; ("intf" "⨍" )
    ;; ("prec" "≺" )
    ;; ("succ" "≻" )
    ;; ("prer" "⊰" )
    ;; ("sucr" "⊱" )
    ;; ("pro" "∷" )


		;; APL
    ("al" "←" )
    ("ar" "→" )
    ("au" "↑" )
    ("ad" "↓" )
    ("lv" "⍅" )
    ("rv" "⍆" )
    ("uv" "⍏" )
    ("dv" "⍖" )
    ("div" "÷" )
    ("x'" "×" )
    ("log" "⍟" )
    ("eqq" "≡" )
    ("neqq" "≢" )
    ("til" "∼" )
    ("p" "⍴" )
    ("w" "⍵" )
    ("i" "⍳" )
    ("ib" "⍸" )
    ("a" "⍺" )
    ("ab" "⍶" )
    ("ain" "∊" )
    ("inb" "⋸" )
    ("fl" "⌊" )
    ("ce" "⌈" )
    ("und" "_" )
    ("delt" "∆" )
    ("del" "∇" )
    ("nab" "∇" )
    ("ou" "⍛" )
    ("T" "⊤" )
    ("dec" "⊥" )
    ("lef" "⊣" )
    ("rig" "⊢" )
    ("dom" "⌹" )
    ("ci" "○" )
    ("ro" "⌽" )
    ("rf" "⊖" )
    ("tra" "⍉" )
    ("xf" "⍀" ) ; expand 1st
    ("rf" "⌿" ) ; reduce 1st
    ("sou" "⍋" )
    ("sod" "⍒" )
    ("aneg" "¯" )
    ("zil" "⍬" )
    ("cob" "⍪" )
    ("fmt" "⍕" )
    ("exc" "⍎" )
    ("at" "@" )
    ("Ib" "⌶" )
    ("dia" "¨" )
    ("strd" "⍣" )
    ("smrk" "⍨" )
    ("hoot" "⍤" )
    ("holl" "⍥" )
    ("qua" "⎕" )
    ("squ" "⌷" )
    ("qe" "⌸" )
    ("qdi" "⌺" )
    ("acom" "⍝" )
    ("acm" "⍝" )


		;; Racket
    ;; ("rt" "#t" )
    ;; ("rf" "#f" )
    ("flx" "⌋" )
    ("cex" "⌉" )
    ("cur" "⫶" ) ; curry
    ("repl" "replicate" )
    ("cat" "concat" )
    ("zipw" "zip-with" )
    ("ir?" "in-range?" )
    ("csae" "case" ) ; catch typo
    ("casea" "case→" )
    ("csaea" "case→" ) ; catch typo
    ("casel" "case-λ" )
    ("csaea" "case→" ) ; catch typo
    ("casel" "case-λ" )
    ("csael" "case-λ" ) ; catch typo
    ("cns" "cons" )
    ("lsit" "list" ) ; catch typo
    ("let" "let*" )
    ("for" "∀:" )
    ("for*" "∀:*" )
    ("forl" "∀:l" )
    ("for*l" "∀:*l" )
    ("forh" "∀:h" )
    ("for*h" "∀:*h" )
    ("forv" "∀:v" )
    ("for*v" "∀:*v" )
    ("fors" "∀:∑" )
    ("for*s" "∀:*∑" )
    ("forp" "∀:∏" )
    ("for*p" "∀:*∏" )
    ("forse" "∀:s" )
    ("for*se" "∀:*s" )
    ("forhe" "∀:hq" )
    ("for*he" "∀:*hq" )
    ("forhv" "∀:hv" )
    ("for*hv" "∀:*hv" )
    ("foro" "∀:or" )
    ("for*o" "∀:*or" )
    ("foran" "∀:and" )
    ("for*an" "∀:*and" )
    ("forfi" "∀:1st" )
    ("for*fi" "∀:*1st" )
    ("forla" "∀:last" )
    ("for*la" "∀:*last" )
    ("forls" "∀:lists" )
    ("for*ls" "∀:*lists" )
    ("forfo" "∀:↰" )
    ("for*fo" "∀:*↰" )
    ("foldl" "↰" )
    ("foldr" "↱" )


    ;; Types

    ("N" "ℕ" )
    ("I" "𝐈" )
    ("Nu" "ℂ" )
    ("Zm" "ℤ⁻" )
    ("Zm0" "ℤ⁰⁻" )
    ("Z" "ℤ" )
    ("Zp0" "ℤ⁰⁺" )
    ("Zp" "ℤ⁺" )
    ("L" "𝑳" )
    ("L'" "𝗟" )
    ;; ("L'" "⊗" )
    ("V" "𝑽" )
    ("V'" "𝗩" )
    ("Pa" "Pair" )
    ;; ("Pa" "⊕" )
    ("M" "𝑴" )
    ("O" "𝑴" )
    ("Rm" "ℝ⁻" )
    ("Rm0" "ℝ⁰⁻" )
    ("R" "ℝ" )
    ("Rp0" "ℝ⁰⁺" )
    ("Rp" "ℝ⁺" )
    ("Tr" "𝑻" )
    ("F" "𝑭" )
    ("B" "𝐁" )
    ("St" "𝕊" )
    ("Sy" "𝑺" )
    ("H" "𝑯" )
    ("Hi" "𝑯i" )
    ("Hm" "𝑯m" )
    ("A" "𝐀" )
    ("Qm" "ℚ⁻" )
    ("Qm0" "ℚ⁰⁻" )
    ("Q" "ℚ" )
    ("Qp0" "ℚ⁰⁺" )
    ("Qp" "ℚ⁺" )
    ("JS" "JSExpr" )
    ("JH" "JSHash" )
    ("JHS" "JSHash Symbol" )

    ;; ("N" "𝐍" )
    ;; ("I" "𝐈" )
    ;; ("Nu" "ℂ" )
    ;; ("Zm" "𝐙⁻" )
    ;; ("Zm0" "𝐙⁰⁻" )
    ;; ("Z" "𝐙" )
    ;; ("Zp0" "𝐙⁰⁺" )
    ;; ("Zp" "𝐙⁺" )
    ;; ("L" "𝑳" )
    ;; ("L'" "𝗟" )
    ;; ;; ("L'" "⊗" )
    ;; ("V" "𝑽" )
    ;; ("V'" "𝗩" )
    ;; ("Pa" "Pair" )
    ;; ;; ("Pa" "⊕" )
    ;; ("M" "𝑴" )
    ;; ("O" "𝑴" )
    ;; ("Rm" "𝐑⁻" )
    ;; ("Rm0" "𝐑⁰⁻" )
    ;; ("R" "𝐑" )
    ;; ("Rp0" "𝐑⁰⁺" )
    ;; ("Rp" "𝐑⁺" )
    ;; ("Tr" "𝑻" )
    ;; ("F" "𝑭" )
    ;; ("B" "𝐁" )
    ;; ("St" "𝕊" )
    ;; ("Sy" "𝑺" )
    ;; ("H" "𝑯" )
    ;; ("Hi" "𝑯i" )
    ;; ("Hm" "𝑯m" )
    ;; ("A" "𝐀" )
    ;; ("Qm" "𝐐⁻" )
    ;; ("Qm0" "𝐐⁰⁻" )
    ;; ("Q" "𝐐" )
    ;; ("Qp0" "𝐐⁰⁺" )
    ;; ("Qp" "𝐐⁺" )
    ;; ("JS" "JSExpr" )
    ;; ("JH" "JSHash" )
    ;; ("JHS" "JSHash Symbol" )

;; ----------------------------------------------

    ;; ("N" "Natural" )
    ;; ("I" "Index" )
    ;; ("Com" "Number" ) ; Complex number
    ;; ("Zm" "Negative-Integer" )
    ;; ("Zm0" "Nonpositive-Integer" )
    ;; ("Z" "Integer" )
    ;; ("Zp0" "Nonnegative-Integer" )
    ;; ("Zp" "Positive-Integer" )
    ;; ("L" "Listof" )
    ;; ("L'" "List" )
    ;; ("V" "Vectorof" )
    ;; ("V'" "Vector" )
    ;; ("Pa" "Pair" )
    ;; ("M" "Maybe" )
    ;; ("O" "Option" )
    ;; ("Rm" "Negative-Float" )
    ;; ("Rm0" "Nonpositive-Float" )
    ;; ("R" "Float" )
    ;; ("Rp0" "Nonnegative-Float" )
    ;; ("Rp" "Positive-Float" )
    ;; ("Rem" "Negative-Real" )
    ;; ("Rem0" "Nonpositive-Real" )
    ;; ("Re" "Real" )
    ;; ("Rep0" "Nonnegative-Real" )
    ;; ("Rep" "Positive-Real" )
    ;; ("Tr" "True" )
    ;; ("F" "False" )
    ;; ("B" "Boolean" )
    ;; ("St" "String" )
    ;; ("Sy" "Symbol" )
    ;; ("H" "HashTable" )
    ;; ("Hi" "ImmutableHashTable" )
    ;; ("Hm" "MutableHashTable" )
    ;; ("Qm" "Negative-Exact-Rational" )
    ;; ("Qm0" "Nonpositive-Exact-Rational" )
    ;; ("Q" "Exact-Rational" )
    ;; ("Qp0" "Nonnegative-Exact-Rational" )
    ;; ("Qp" "Positive-Exact-Rational" )
    ;; ("JS" "JSExpr" )
    ;; ("JH" "JSHash" )
    ;; ("JHS" "JSHash Symbol" )



    ;; url
    ("urlemacs" "http://ergoemacs.org/" )

    ;;
    ))

;; define abbrev for specific major mode
;; the first part of the name should be the value of the variable major-mode of that mode
;; e.g. for go-mode, name should be go-mode-abbrev-table

(when (boundp 'go-mode-abbrev-table)
  (clear-abbrev-table go-mode-abbrev-table))

(define-abbrev-table 'go-mode-abbrev-table
  '(
    ("go" "package main
import \"fmt\"
func main() {
        fmt.Println(\"3\")
}")

    ("p" "fmt.Printf(\"%v\\n\", hh▮)")
    ("pl" "fmt.Println(hh▮)")
    ("r" "return")
    ("st" "string")
    ("eq" "==")
    ("v" "var x = 3")
    ("df" "x := 3")
    ("c" "const x = 3")
    ("f" "func ff(x int) int {
    return nil
}")
    ("if" "if 4 { 3 }")
    ("ie" " if err != nil { panic(err) }")
    ("ei" "else if x > 0 { 3 }")
    ("else" "else { 3 }")
    ("for" "for i := 0; i < 4; i++ { i }")
    ("fr" "for k, v := range xxx {
▮
    }
")
    ;;

    ))

(set-default 'abbrev-mode t)


(setq save-abbrevs nil)
