#mark: Z; gotomark: z or "<register>z
#colorscheme solarized-dark

## disable clippy:
set-option -add global ui_options terminal_assistant=none
add-highlighter global/ wrap -word -indent #fixme

# Always keep one line and three columns displayed around the cursor
set-option global scrolloff 1,3

declare-user-mode quit
map global quit X "<esc>:wq<ret>"
map global quit Q "<esc>:q!<ret>"
map global normal X ":enter-user-mode quit<ret>"
#map global insert f "<esc>:enter-user-mode quit<ret>d<ret>"
map global goto a <esc>gh
map global goto L <esc>A
map global goto H <esc>I
map global goto A <esc>I
map global normal <c-k> 10k
map global normal <c-j> 10j
#map global normal "XQ" ":wq" #how to input sequence like "XQ" (if even possible)?

# Display line numbers
add-highlighter global/ number-lines -hlcursor

# Clipboard management mappings
map global user y '<a-|>wl-copy<ret>'
map global user p '<a-!>wl-paste<ret>'
map global user P -docstring 'paste before' "<a-!>wl-paste<ret>"


set global idle_timeout 300 #for e.g. <fd>

## <fd> quickly for <escape>:
## bad solution b/c e.g. "fed" will still exit insert mode when pressed quickly;
## this is ghetto and should be replaced online
#hook global InsertChar f %{
#  map buffer insert d <backspace><esc>
#  hook -once buffer InsertIdle .* %{
#    unmap buffer insert d
#  }
#}

## <XX> quickly for <:wq>:
#hook global NormalKey X %{
#  map buffer normal X :wq<ret>
#  hook -once buffer NormalIdle .* %{
#    unmap buffer normal X
#  }
#}

## <XQ> quickly for <:wq>:
## the following must be modified to account for the fact that
#Q is already assigned to "records macro", and the "fd" and "XX"
# solutions depend on the fact that the "f", "d", and "X"
# keypresses not having prior assignments in the modes in which
# they're being used here.
# global NormalKey X %{
#  map buffer normal Q :q!<ret>
#  hook -once buffer NormalIdle .* %{
#    unmap buffer insert Q
#  }
#}

# set cursor to underline
hook global InsertIdle .* %{
  set-face window PrimaryCursor default,default+u
  set-face window PrimaryCursorEol default,default+u
  set-face window SecondaryCursor default,default+u
  set-face window SecondaryCursorEol default,default+u
  set-face window LineNumberCursor default,default+u
  set-face window PrimarySelection default,default+u
  set-face window SecondarySelection default,default+u
}

# set cursor to default
hook global NormalIdle .* %{
  set-face window PrimaryCursor default,default+r
  set-face window PrimaryCursorEol default,default+r
  set-face window SecondaryCursor default,default+r
  set-face window SecondaryCursorEol default,default+r
  set-face window LineNumberCursor default,default+r
  set-face window PrimarySelection default,default+r
  set-face window SecondarySelection default,default+r
}

## Define custom faces to keep them organized
#set-face global PrimaryCursorNormal +r
#set-face global PrimaryCursorInsert bright-magenta+r
#set-face global PrimaryCursor PrimaryCursorNormal

# EOL cursor
set-face global PrimaryCursorEolNormal default,bright-cyan
set-face global PrimaryCursorEolInsert PrimaryCursorInsert
set-face global PrimaryCursorEol PrimaryCursorEolNormal

hook global ModeChange (push|pop):.*insert %{
	set-face window PrimaryCursor PrimaryCursorInsert
	set-face window PrimaryCursorEol PrimaryCursorEolInsert
}

hook global ModeChange (push|pop):insert:.* %{
	set-face window PrimaryCursor PrimaryCursorNormal
	set-face window PrimaryCursorEol PrimaryCursorEolNormal
}

