



==== Nix learning objectives:
. how do we set up and configure a sandbox environment (for ensuring that a given project doesn’t mess up the wider environment, or to use other package managers, like pip, whose operations are usually blocked by NixOS)?

. how do we nixify a given free package?

. how do we wrap (nixify) proprietary packages, e.g., Dyalog APL? how do we find out the dependencies?

. How to write a package and add it to the official nixpkgs

. why can't I install e.g. `dapl` by doing `inst nixos.dapl`, as instructed by search.nixos.org? do I need to add or switch to another channel? nixos.dapl, nixos.haskellPackages.orthotope, nixos.ngn-k

. how to install easy-purescript-nix system-wide rather than having to use a nix-shell? (involves configuration.nix)

. How to set up a FHS-compatible environment and use it to enable proper functioning of 3rd-party binaries


. How to fix a broken package in Nixpkgs

. how to use Nick's search-nixpkgs tool to quickly search nixpkgs offline?

. How to patch 3rd-party binaries using e.g. PatchELF



==== What makes Nix hard:
If I build two copies of emacs from two slightly different derivations, how can I efficiently test the differences between the resulting binaries?


First, when Nix runs a builder, it initially clears the environment (except for the attributes declared in the derivation). “For instance, the PATH variable is empty. This is done to prevent undeclared inputs from being used in the build process. If e.g. the PATH contained /usr/bin, then you might accidentally use /usr/bin/gcc”. As opposed to what, though? Does it just mean “as opposed to a different desired version of gcc”?

Paths can also be specified between angle brackets, e.g. <nixpkgs>. This means that the directories listed in the environment variable NIX_PATH will be searched for the given file or directory name. Does this mean that < > always corresponds specifically to NIX_PATH? So in this example, <nixpkgs> would refer to the first file or folder found when searching through the paths listed in the NIX_PATH variable?

An @-pattern provides a means of referring to the whole value being matched:

       `args@{ x, y, z, ... }: z + y + x + args.q`
       but can also be written as:

       `{ x, y, z, ... } @ args: z + y + x + args.q`
Here `args` is bound to the entire argument which is further matched against the pattern `{ x, y, z, … }`. @-pattern mainly makes sense with an ellipsis(…) as you can access attribute names as `q`, using `args.q,` which was given as an additional attribute to the function.

The args@ expression is bound to the argument passed to the function which means that attributes with defaults that aren't explicitly specified in the function call won't cause an evaluation error, but won't exist in args.

For instance
[source,nix]
----
    let
      function = args@{ a ? 23, ... }: args;
    in
      function {}
----
will evaluate to an empty attribute set.
??? how does this work?

An import expression evaluates to the value of the
  # file that it imports.
  `(import /tmp/foo.nix)`

What does mkDerivation output? A .nix file? Apparently not, since here it looks like it outputs a directory…?
`minicondaScript = pkgs.stdenv.mkDerivation rec {…}`
`${minicondaScript}/miniconda.sh`

==== Derivations
??? "What" happens if we pass arbitrary attributes besides those listed (name, system, builder, etc.)? It doesn’t give an error (tested this), so how do we reference their corresponding env variables? Are their values just copied to attributes of the same names?
  `inherit (import ../../.. { inherit config; }) pkgs;`
??? what’s happening here? Usually we say a = `import …` or `inherit (name)`. Is there a name here?
It looks like this is either specifying which `pkgs` attribute to inherit, or `pkgs` is itself a list of attributes to inherit

If the build was successful, Nix scans each output path for references to input paths by looking for the hash parts of the input paths. Since these are potential runtime dependencies, Nix registers them as dependencies of the output paths.  ???

Nix-env: how do we prevent a user environment conflict when using `nix-env --install --preserve-installed`?

* The ‘with’ language construct is now more lazy. It only evaluates its argument if a variable might actually refer to an attribute in the argument. For instance, this now works:
[source,nix]
----
    let
      pkgs = with pkgs; { foo = "old"; bar = foo; } // overrides;
      overrides = { foo = "new"; };
    in pkgs.bar
----
This evaluates to `"new"`, while previously it gave an `“infinite recursion”` error.

??? Where is the recursion? The value of the pkgs attribute is being set to { foo = “old”; bar = foo; } // { foo = “new” }. Even if an attribute of pkgs had been referenced afterward, I still don’t see the recursion. The evaluation of the pkgs.bar attribute doesn’t seem to introduce any recursion. So it’s saying that the ‘with pkgs’ statement isn’t evaluating since nothing within the same scope refers to any attribute of pkgs, and that if ‘with pkgs’ had been evaluated, we’d have infinite recursion somewhere. It’s like saying that ‘x = x + 1’ is infinite recursion...

* You can also give a Nix expression on the command line:
[source,nix]
----
           $ nix-instantiate -E 'with import <nixpkgs> { }; hello'
           /nix/store/j8s4zyv75a724q38cb0r87rlczaiag4y-hello-2.8.drv
----
       This is equivalent to:
           $ nix-instantiate '<nixpkgs>' -A hello       ???

--add-root path
           Causes the result of a realisation (--realise and --force-realise) to be registered as a root of the garbage collector.
           The root is stored in path, which must be inside a directory that is scanned for roots by the garbage collector (i.e.,
           typically in a subdirectory of /nix/var/nix/gcroots/) unless the --indirect flag is used.

Using packageOverrides, it is possible to manage packages declaratively. This means that we can list all of our desired packages within a declarative Nix expression. For example, to have aspell, bc, ffmpeg, coreutils, gdb, nixUnstable, emscripten, jq, nox, and silver-searcher, we could use the following in ~/.config/nixpkgs/config.nix:
[source,nix]
----
{
  packageOverrides = pkgs: with pkgs; {
    myPackages = pkgs.buildEnv {
      name = "my-packages";
      paths = [
        aspell
        ...
        silver-searcher
      ];
    };
  };
}
----
	??? Isn’t everything about nix declarative? What does `packageOverrides` do exactly?

You can define a function called packageOverrides in your local ~/.config/nixpkgs/config.nix to override Nix packages. It must be a function that takes pkgs as an argument and returns a modified set of packages.
[source,nix]
----
{
  packageOverrides = pkgs: rec {
    foo = pkgs.foo.override { ... };
  };
}
----
	??? `foo.override`? Is this a hypothetical function? Did we have to write it ourselves, or do most/all packages in nixpkgs have their own override attribute?

Why can the derivation function produce multiple output paths? When do you ever need more than one?

 Much like the usual .drv, except that there's a list of arguments in there passed to the builder (bash) with builder.sh… In the nix store..? Nix automatically copies files or directories needed for the build into the store to ensure that they are not changed during the build process and that the deployment is stateless and independent of the building machine. builder.sh is not only in the arguments passed to the builder, it's also in the input derivations.
???

How to get NixOS to replace the old builder.sh in Nix store after I’ve edited the local ./builder.sh?
When does it copy it in the first place? As part of doing nix-instantiate?
How to get “nix-shell hello.nix” to set up the right environment based on the current files grouped with hello.nix, rather than those copied previously to the nix store?

First of all, we were able to source `builder.sh` because it was in our current directory, but that's not nice. We want the builder.sh that is stored in the nix store, the one that would be used by nix-build. To do so, the right way is to pass the usual environment variable through the derivation.  (Nix Pill #10)
???
