// Nix Notes

==== To add a package_ to the Nix Packages collection, we generally need to do 3 things:
  . Write a Nix expression for the package. This is a file that describes all the inputs involved in building the package, such as dependencies, sources, etc. Specifically, it describes the human-readable name of the package, where to order it from, how to unpack it, and what environment tools we need in order to build it (the tools are the function args), and what tools need to be passed to the builder script.
  . Write a _builder_. This is a shell script that actually builds the package from the inputs. Specifically, it tells
    .. what standard environment (standard toolbox) should be used (done by calling the setup script of the standard environment -- this begins by clearing the normal user environment variables out of scope so none are accidentally used),
    .. how to unpack the source file (e.g. tar xvfz $src),
    .. where to find any tools that were unpacked from the source,
    .. what the at-home ingredients should be and where to find each (e.g., cd hello-*; ./configure --prefix=$out),
    .. the recipe for actually building the package (e.g., make), and
    .. where to put everything when the product has been built (e.g, make install).
 . Add the package to the file pkgs/top-level/all-packages.nix. The Nix expression written in the first step is a _function_; it requires other packages in order to build it. In this step you put it all together, i.e., you call the function with the right args to build the actual package.

- Remember: all uses of colons are just to specify function arguments, and functions are always anonymous, and can only be “implicitly named” by assigning the function to an attribute (like dfns in APL).

==== Lists
- Lists are formed by enclosing a whitespace-separated list of values between square brackets. For example,
     `[ 123 ./foo.nix "abc" (f { x = expr; }) ]`
defines a list of four elements, the last being the result of a call to the function f. Note that function calls have to be enclosed in parentheses. If they had been omitted, e.g.,
    `[ 123 ./foo.nix "abc" f { x = expr; } ]`
the result would be a list of five elements, the fourth one being a function and the fifth being a set.

- Note that lists are only lazy in values, and they are strict in length.

==== Sets
- Sets are really the core of the language, since ultimately the Nix language is all about creating derivations, which are really just sets of attributes to be passed to build scripts.

- Sets are just a list of name/value pairs (called attributes) enclosed in curly brackets, where each value is an arbitrary expression terminated by a semicolon. For example:
     { x = 123;
     text = "Hello";
     y = f { bla = 456; };
     }
This defines a set with attributes named x, text, y. The order of the attributes is irrelevant. An attribute name may only occur once.

Attributes can be selected from a set using the . operator. For instance,
    `{ a = "Foo"; b = "Bar"; }.a`
evaluates to "Foo". It is possible to provide a default value in an attribute selection using the or keyword. For example,
    `{ a = "Foo"; b = "Bar"; }.c or "Xyzzy"`
will evaluate to "Xyzzy" because there is no c attribute in the set.

You can use arbitrary double-quoted strings as attribute names:
    `{ "foo ${bar}" = 123; "nix-1.0" = 456; }."foo ${bar}"`
This will evaluate to 123 (assuming bar is antiquotable). In the case where an attribute name is just a single antiquotation, the quotes can be dropped:
    `{ foo = 123; }.${bar} or 456`
This will evaluate to 123 if bar evaluates to "foo" when coerced to a string and 456 otherwise (again assuming bar is antiquotable).

In the special case where an attribute name inside of a set declaration evaluates to null (which is normally an error, as null is not antiquotable), that attribute is simply not added to the set:
     `{ ${if foo then "bar" else null} = true; }`
This will evaluate to {} if foo evaluates to false.

==== __functor
A set that has a `__functor` attribute whose value is callable (i.e. is itself a function or a set with a `__functor` attribute whose value is callable) can be applied as if it were a function, with the set itself implicitly passed in first , e.g.,
[source,nix]
----
    let add = { __functor = self: x: x + self.x; };
      inc = add // { x = 1; };
    in inc 1
----
evaluates to 2. This can be used to attach metadata to a function without the caller needing to treat it specially, or to implement a form of object-oriented programming, for example.


==== Functions:
[source,nix]
----
    let concat = { x, y }: x + y;
    in concat { x = "foo"; y = "bar"; }

    let negate = x: !x;
        concat = x: y: x + y;
    in if negate true then concat "foo" "bar" else ""
----

- Note that functions do not have names. If you want to “give them a name”, you can bind them to an attribute, so the attribute itself effectively becomes the name of the function, e.g. the attribute “concat” here...
let concat = { x, y }: x + y;
in concat { x = "foo"; y = "bar"; }

==== Conditionals
Conditionals look like this:
    `if e1 then e2 else e3`
where e1 is an expression that should evaluate to a Boolean value (true or false).

==== Assertions
Assertions are generally used to check that certain requirements on or between features and dependencies hold. They look like this:
    `assert e1; e2`
where e1 is an expression that should evaluate to a Boolean value. If it evaluates to true, e2 is returned; otherwise expression evaluation is aborted and a backtrace is printed.

    `assert a --> b`
means “verify that a implies b, i.e., that if a is true, then b is true”

==== With-expressions
With-expressions bring into scope [the members of this given set], i.e., inherit the stuff _inside_ this given set, i.e., set them as attributes
A with-expression,
    `with e1; e2`
introduces the set e1 into the lexical scope of the expression e2. For instance,
    `let as = { x = "foo"; y = "bar"; };`
    `in with as; x + y`          # inherit everything in the set “as”  -- same as inherit as.x; inherit as.y
evaluates to "foobar" since the with adds the x and y attributes of as to the lexical scope in the expression x + y. The most common use of with is in conjunction with the import function. E.g.,
    `with (import ./definitions.nix); ...`
makes all attributes defined in the file definitions.nix available as if they were defined locally in a let-expression.

==== Comments
Comments can be single-line, started with a # character, or inline/multi-line, enclosed within /* ... */.

==== Derivation
- The most important built-in function is derivation, which is used to describe a single derivation (i.e., a build action). It takes as input a set, the attributes of which specify the inputs of the build.

. There must be an attribute named system whose value must be a string specifying a Nix platform identifier, such as "i686-linux" or "x86_64-darwin"[7] The build can only be performed on a machine and operating system matching the platform identifier. (Nix can automatically forward builds for other platforms by forwarding them to other machines; see Chapter 16, Remote Builds.)
. There must be an attribute named name whose value must be a string. This is used as a symbolic name for the package by nix-env, and it is appended to the output paths of the derivation.
. There must be an attribute named builder that identifies the program that is executed to perform the build. It can be either a derivation or a source (a local file reference, e.g., ./builder.sh).
. Every attribute is passed as an environment variable to the builder. Attribute values are translated to environment variables as follows:

- Strings and numbers are just passed verbatim.

- A path (e.g., ../foo/sources.tar) causes the referenced file to be copied to the store; its location in the store is put in the environment variable. The idea is that all sources should reside in the Nix store, since all inputs to a derivation should reside in the Nix store.

- A derivation causes that derivation to be built prior to the present derivation; its default output path is put in the environment variable.

- Lists of the previous types are also allowed. They are simply concatenated, separated by spaces.

- true is passed as the string 1, false and null are passed as an empty string.

- The optional attribute args specifies command-line arguments to be passed to the builder. It should be a list.

- The optional attribute outputs specifies a list of symbolic outputs of the derivation. By default, a derivation produces a single output path, denoted as out. However, derivations can produce multiple output paths. This is useful because it allows outputs to be downloaded or garbage-collected separately. For instance, imagine a library package that provides a dynamic library, header files, and documentation. A program that links against the library doesn’t need the header files and documentation at runtime, and it doesn’t need the documentation at build time. Thus, the library package could specify:

`outputs = [ "lib" "headers" "doc" ];`
This will cause Nix to pass environment variables lib, headers and doc to the builder containing the intended store paths of each output. The builder would typically do something like
    `./configure --libdir=$lib/lib --includedir=$headers/include --docdir=$doc/share/doc`
for an Autoconf-style package. You can refer to each output of a derivation by selecting it as an attribute, e.g.
    `buildInputs = [ pkg.lib pkg.headers ];`
The first element of outputs determines the default output. Thus, you could also write
    `buildInputs = [ pkg pkg.headers ];`
- The function mkDerivation in the Nixpkgs standard environment is a wrapper around derivation that adds a default value for system and always uses Bash as the builder, to which the supplied builder is passed as a command-line argument.

- Paths can also be specified between angle brackets, e.g. <nixpkgs>. This means that the directories listed in the environment variable NIX_PATH will be searched for the given file or directory name.

- To install [myPackages] into our environment, you can just run nix-env -iA nixpkgs.myPackages. If you want to load the packages to be built from a working copy of nixpkgs you just run nix-env -f. -iA myPackages.

- The Nix expression in Example 14.1, “Nix expression for GNU Hello (default.nix)” is a function; it is missing some arguments that have to be filled in somewhere. In the Nix Packages collection this is done in the file pkgs/top-level/all-packages.nix, where all Nix expressions for packages are imported and called with the appropriate arguments.


==== Building and Testing
- You can now try to build Hello. Of course, you could do nix-env -i hello, but you may not want to install a possibly broken package just yet. The best way to test the package is by using the command nix-build, which builds a Nix expression and creates a symlink named result in the current directory:
----
$ nix-build -A hello
building path `/nix/store/632d2b22514d...-hello-2.1.1'
hello-2.1.1/
hello-2.1.1/intl/
hello-2.1.1/intl/ChangeLog
...

$ ls -l result
lrwxrwxrwx ... 2006-09-29 10:43 result -> /nix/store/632d2b22514d...-hello-2.1.1

$ ./result/bin/hello
Hello, world!
----

The -A option selects the hello attribute (in all-packages.nix). This is faster than using the symbolic package name specified by the name attribute (which also happens to be hello) and is unambiguous (there can be multiple packages with the symbolic name hello, but there can be only one attribute in a set named hello).

nix-build registers the ./result symlink as a garbage collection root, so unless and until you delete the ./result symlink, the output of the build will be safely kept on your system. You can use nix-build’s -o switch to give the symlink another name.

Nix-shell drops us in a shell with the same (or almost) environment used to run the builder.

nix-shell builds the .drv file and its input dependencies, then drops into a shell by setting up the environment variables necessary to build the .drv, in particular those passed to the derivation function.
