(deftheme harmonic-dark-cac
  "Created 2020-11-20.")

(custom-theme-set-faces
 'harmonic-dark-cac
 '(default ((t (:family "Fira Code" :foundry "CTDB" :width normal :height 98 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#cbd6e2" :background "#0b1c2c" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#bf8b56"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#8b56bf"))))
 '(highlight ((t (:background "#223b54"))))
 '(region ((t (:extend t :background "#405c79"))))
 '(shadow ((t (:foreground "#627e99"))))
 '(secondary-selection ((t (:extend t :background "#627e99"))))
 '(trailing-whitespace ((t (:foreground "#8bbf56" :background "#A7ABB2"))))
 '(font-lock-builtin-face ((t (:foreground "#568bbf"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#405c79"))))
 '(font-lock-comment-face ((t (:underline nil :foreground "#A7ABB2" :inherit (italic)))))
 '(font-lock-constant-face ((t (:underline nil :foreground "#73777D" :inherit (italic)))))
 '(font-lock-doc-face ((t (:foreground "#aabcce"))))
 '(font-lock-function-name-face ((t (:foreground "#8b56bf"))))
 '(font-lock-keyword-face ((t (:weight normal :underline nil :foreground "#73777D" :inherit (italic)))))
 '(font-lock-negation-char-face ((t (:foreground "#56bf8b"))))
 '(font-lock-preprocessor-face ((t (:foreground "#8b56bf"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#8bbf56"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#bf568b"))))
 '(font-lock-string-face ((t (:foreground "#56bf8b"))))
 '(font-lock-type-face ((t (:foreground "#8bbf56"))))
 '(font-lock-variable-name-face ((t (:foreground "#bf8b56"))))
 '(font-lock-warning-face ((t (:foreground "#bf8b56"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#8b56bf"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#bf568b"))))
 '(fringe ((t (:background "#0b1c2c"))))
 '(header-line ((t (:foreground "#bf568b" :inherit (mode-line)))))
 '(tooltip ((t (:background "#223b54" :inherit (default)))))
 '(mode-line ((t (:box nil :foreground "#aabcce" :background "#405c79"))))
 '(mode-line-buffer-id ((t (:foreground "#56bf8b"))))
 '(mode-line-emphasis ((t (:slant italic :foreground "#e5ebf1"))))
 '(mode-line-highlight ((t (:weight bold :box nil :foreground "#bf568b"))))
 '(mode-line-inactive ((t (:box nil :foreground "#627e99" :background "#223b54"))))
 '(isearch ((t (:inverse-video t :foreground "#8bbf56" :background "#223b54"))))
 '(isearch-fail ((t (:inverse-video t :background "#223b54" :inherit (font-lock-warning-face)))))
 '(lazy-highlight ((t (:inverse-video t :foreground "#568bbf" :background "#223b54"))))
 '(match ((t (:inverse-video t :foreground "#8b56bf" :background "#223b54"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(racket-keyword-argument-face ((t (:foreground "#ff5874"))))
 '(magit-log-author ((t (:foreground "#7fdbca" :slant normal :weight normal)))))

(provide-theme 'harmonic-dark-cac)
