(deftheme night-owl-cac
  "Created 2020-11-20.")

(custom-theme-set-faces
 'night-owl-cac
 '(default ((t (:family "Fira Code" :foundry "CTDB" :width normal :height 98 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#d6deeb" :background "#011627" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#80a4c2"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#c792ea"))))
 '(highlight ((t (:background "#010f1d"))))
 '(region ((t (:extend t :background "#405c79"))))
 '(shadow ((t (:foreground "#627e99"))))
 '(secondary-selection ((t (:extend t :background "#627e99"))))
 '(trailing-whitespace ((t (:foreground "#8bbf56" :background "#A7ABB2"))))
 '(font-lock-builtin-face ((t (:foreground "#82aaff"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#405c79"))))
 '(font-lock-comment-face ((t (:underline nil :foreground "#A7ABB2" :inherit (italic)))))
 '(font-lock-constant-face ((t (:underline nil :foreground "#f58c6c" :inherit (italic)))))
 '(font-lock-doc-face ((t (:foreground "#aabcce"))))
 '(font-lock-function-name-face ((t (:foreground "#c792ea"))))
 '(font-lock-keyword-face ((t (:slant italic :underline nil :foreground "#c792ea" :inherit nil))))
 '(font-lock-negation-char-face ((t (:foreground "#56bf8b"))))
 '(font-lock-preprocessor-face ((t (:foreground "#8b56bf"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#8bbf56"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#bf568b"))))
 '(font-lock-string-face ((t (:foreground "#ffcb8a"))))
 '(font-lock-type-face ((t (:foreground "#8bbf56"))))
 '(font-lock-variable-name-face ((t (:foreground "#7fdbca"))))
 '(font-lock-warning-face ((t (:foreground "#bf8b56"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#8b56bf"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#bf568b"))))
 '(fringe ((t (:background "#011627"))))
 '(header-line ((t (:foreground "#bf568b" :inherit (mode-line)))))
 '(tooltip ((t (:background "#223b54" :inherit (default)))))
 '(mode-line ((t (:box nil :foreground "#d6deeb" :background "#0b2942"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#d6deeb"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box nil))))
 '(mode-line-inactive ((t (:box (:line-width 1 :color "#5f7e97" :style nil) :foreground "#676e95" :background "#011627"))))
 '(isearch ((t (:inverse-video t :foreground "#8bbf56" :background "#223b54"))))
 '(isearch-fail ((t (:inverse-video t :background "#223b54" :inherit (font-lock-warning-face)))))
 '(lazy-highlight ((t (:inverse-video t :foreground "#568bbf" :background "#223b54"))))
 '(match ((t (:inverse-video t :foreground "#8b56bf" :background "#223b54"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(helm-source-header ((t (:extend t :foreground "#011627" :background "#9e7dd8"))))
 '(helm-selection ((t (:extend t :background "#1d3b53"))))
 '(helm-ff-directory ((t (:extend t :foreground "#82aaff"))))
 '(line-number ((t (:inherit default :background "#011627" :foreground "#4b6479"))))
 '(line-number-current-line ((t (:inherit line-number :background "#011627" :foreground "#d6deeb"))))
 '(rainbow-delimiters-depth-1-face ((t (:inherit rainbow-delimiters-base-face :foreground "grey55"))))
 '(rainbow-delimiters-depth-2-face ((t (:inherit rainbow-delimiters-base-face :foreground "#93a8c6"))))
 '(rainbow-delimiters-depth-3-face ((t (:inherit rainbow-delimiters-base-face :foreground "#b0b1a3"))))
 '(rainbow-delimiters-depth-4-face ((t (:inherit rainbow-delimiters-base-face :foreground "#97b098"))))
 '(rainbow-delimiters-depth-5-face ((t (:inherit rainbow-delimiters-base-face :foreground "#aebed8"))))
 '(rainbow-delimiters-depth-6-face ((t (:inherit rainbow-delimiters-base-face :foreground "#b0b0b3"))))
 '(rainbow-delimiters-depth-7-face ((t (:inherit rainbow-delimiters-base-face :foreground "#90a890"))))
 '(rainbow-delimiters-depth-8-face ((t (:inherit rainbow-delimiters-base-face :foreground "#a2b6da"))))
 '(rainbow-delimiters-depth-9-face ((t (:inherit rainbow-delimiters-base-face :foreground "#9cb6ad")))))

(provide-theme 'night-owl-cac)
